import { defineStore } from "pinia";
import { LocalStorage } from "src/services/storage";

const languageKey = "app_language";
const themeKey = "app_theme";
const currencyKey = "currency_code";

const applyTheme = (theme) => {
  const nextTheme = theme === "light" ? "light" : "dark";
  document.documentElement.dataset.theme = nextTheme;
  document.documentElement.classList.toggle("dark", nextTheme === "dark");
  document.documentElement.classList.toggle("light", nextTheme === "light");
};

const copy = {
  ru: {
    tabs: {
      home: "Главная",
      search: "Поиск",
      cart: "Корзина",
      track: "Трекинг",
      account: "Профиль",
    },
    home: {
      delivery: "Доставка",
      pick: "Выбор сегодня",
      hero: "Рестораны рядом, доставка прямо к вам.",
      loading: "Загружаем рестораны Tagam Delivery.",
      offers: "Смотреть предложения",
      popular: "Популярное рядом",
      viewAll: "Все",
      couldNotLoad: "Не удалось загрузить рестораны",
      retry: "Повторить",
      emptyTitle: "Рестораны не вернулись",
      emptyText: "Сервер ответил успешно, но список пуст.",
      freeDelivery: "Бесплатная доставка",
      deliveryAvailable: "Доставка доступна",
      newRating: "Новый",
      all: "Все",
      clear: "Очистить",
    },
    search: {
      title: "Поиск",
      placeholder: "Ресторан, кухня или блюдо",
      clear: "Очистить",
      failed: "Поиск не загрузился",
      restaurants: "Рестораны",
      dishes: "Блюда",
      indexed: "В индексе",
      quick: "Быстрый поиск",
      open: "Открыть",
      emptyTitle: "Ничего не найдено",
      emptyText: "Попробуйте название кухни, ресторана или блюда из реального меню.",
    },
    account: {
      title: "Профиль",
      action: "Настройки",
      customer: "Клиент Tagam",
      subtitle: "Бонусы, кошелек и сохраненные адреса",
      preferences: "Настройки приложения",
      language: "Язык",
      theme: "Тема",
      dark: "Темная",
      light: "Светлая",
      done: "Готово",
      appliesImmediately: "Изменения сразу применяются ко всему приложению.",
      metrics: ["Бонусные баллы", "Баланс кошелька", "Сохраненные места", "Повторные заказы"],
      menu: ["Заказы", "Платежи", "Адреса", "Уведомления", "Язык и тема"],
    },
    location: {
      title: "Выберите адрес",
      action: "Локация",
      guestTitle: "Аккаунт можно создать позже",
      guestText:
        "Сейчас нужен только адрес доставки. Регистрация понадобится позже для сохраненных адресов, истории заказов, кошелька и оплаты.",
      login: "Войти",
      guest: "Как гость",
      mapHint: "Выберите точку на карте",
      pinTitle: "Поставьте пин на карту",
      checking: "Проверяем адрес...",
      confirm: "Подтвердить локацию",
    },
    restaurant: {
      save: "Сохранить ресторан",
      unavailable: "Ресторан недоступен",
      retry: "Повторить",
      newRating: "Новый",
      distance: "Расстояние",
      distanceAway: "от вас",
      deals: "Акции",
      noDeals: "Без акций",
      items: "Блюда",
      menuEmpty: "Меню пустое",
      menuEmptyText: "Ресторан доступен, но блюда сейчас не опубликованы.",
      itemCount: "блюд",
      sale: "Скидка",
      noDescription: "Описание скоро появится",
      openItem: "Открыть блюдо",
      cart: "Корзина",
      km: "км",
      from: "от",
      popular: "Популярное",
      menu: "Меню",
      deliveryAvailable: "Доставка доступна",
    },
    tracking: {
      title: "Трекинг заказа",
      action: "Чат",
      eta: "Приедет через 12 мин",
      headline: "Курьер рядом с проспектом Нейтралитета.",
      liveRoute: "Живой маршрут",
      steps: [
        ["Ресторан принял заказ", "Кухня начала готовить", true],
        ["Курьер забрал заказ", "Маршрут и чат включены", true],
        ["Почти у вас", "Подготовьтесь к бесконтактной передаче", false],
      ],
    },
  },
  tk: {
    tabs: {
      home: "Baş sahypa",
      search: "Gözleg",
      cart: "Sebet",
      track: "Gözegçilik",
      account: "Profil",
    },
    home: {
      delivery: "Eltip bermek",
      pick: "Şu gün saýlanan",
      hero: "Ýakyndaky restoranlar, eltip bermek göni size.",
      loading: "Tagam Delivery restoranlary ýüklenýär.",
      offers: "Teklipleri gör",
      popular: "Ýakynda meşhur",
      viewAll: "Ählisi",
      couldNotLoad: "Restoranlary ýükläp bolmady",
      retry: "Gaýtadan synan",
      emptyTitle: "Restoran ýok",
      emptyText: "Serwer üstünlikli jogap berdi, emma sanaw boş.",
      freeDelivery: "Mugt eltip bermek",
      deliveryAvailable: "Eltip bermek bar",
      newRating: "Täze",
      all: "Ählisi",
      clear: "Arassala",
    },
    search: {
      title: "Gözleg",
      placeholder: "Restoran, aşhana ýa-da nahar",
      clear: "Arassala",
      failed: "Gözleg ýüklenmedi",
      restaurants: "Restoranlar",
      dishes: "Naharlar",
      indexed: "Indeksde",
      quick: "Çalt gözleg",
      open: "Aç",
      emptyTitle: "Netije tapylmady",
      emptyText: "Hakyky menýudan aşhanany, restorany ýa-da nahary synap görüň.",
    },
    account: {
      title: "Profil",
      action: "Sazlamalar",
      customer: "Tagam müşderisi",
      subtitle: "Bonuslar, gapjyk we saklanan salgylar",
      preferences: "Programma sazlamalary",
      language: "Dil",
      theme: "Tema",
      dark: "Garaňky",
      light: "Ýagty",
      done: "Taýýar",
      appliesImmediately: "Üýtgeşmeler tutuş programma derrew ulanylýar.",
      metrics: ["Bonus ballary", "Gapjyk balansy", "Saklanan ýerler", "Gaýtadan sargyt"],
      menu: ["Sargytlar", "Tölegler", "Salgylar", "Habarnamalar", "Dil we tema"],
    },
    location: {
      title: "Salgyny saýlaň",
      action: "Ýerleşiş",
      guestTitle: "Hasaby soň döredip bilersiňiz",
      guestText:
        "Häzir diňe eltip bermek salgysy gerek. Hasaba alyş soň saklanan salgylar, sargyt taryhy, gapjyk we töleg üçin gerek bolar.",
      login: "Gir",
      guest: "Myhman hökmünde",
      mapHint: "Kartadan nokat saýlaň",
      pinTitle: "Kartada bellik goýuň",
      checking: "Salgy barlanýar...",
      confirm: "Ýerleşişi tassykla",
    },
    restaurant: {
      save: "Restorany sakla",
      unavailable: "Restoran elýeterli däl",
      retry: "Gaýtadan synan",
      newRating: "Täze",
      distance: "Aralyk",
      distanceAway: "sizden",
      deals: "Aksiýalar",
      noDeals: "Aksiýa ýok",
      items: "Tagamlar",
      menuEmpty: "Menýu boş",
      menuEmptyText: "Restoran elýeterli, ýöne häzir tagamlar çap edilmedi.",
      itemCount: "tagam",
      sale: "Arzanladyş",
      noDescription: "Düşündiriş ýakynda peýda bolar",
      openItem: "Tagamy aç",
      cart: "Sebet",
      km: "km",
      from: "başlap",
      popular: "Meşhur",
      menu: "Menýu",
      deliveryAvailable: "Eltip bermek bar",
    },
    tracking: {
      title: "Sargydy yzarlamak",
      action: "Çat",
      eta: "12 minutdan geler",
      headline: "Kurýer Bitaraplyk şaýolunyň ýanynda.",
      liveRoute: "Janly ugur",
      steps: [
        ["Restoran sargydy kabul etdi", "Aşhana sargydy taýýarlap başlady", true],
        ["Kurýer sargydy aldy", "Janly ugur we çat açyk", true],
        ["Tiz wagtda ýanyňyzda", "Aragatnaşyksyz gowşuryşa taýýar boluň", false],
      ],
    },
  },
  en: {
    tabs: {
      home: "Home",
      search: "Search",
      cart: "Cart",
      track: "Track",
      account: "Account",
    },
    home: {
      delivery: "Delivery",
      pick: "Today's pick",
      hero: "Nearby restaurants, delivered to you.",
      loading: "Loading Tagam Delivery restaurants.",
      offers: "Explore offers",
      popular: "Popular nearby",
      viewAll: "View all",
      couldNotLoad: "Could not load restaurants",
      retry: "Retry",
      emptyTitle: "No restaurants returned",
      emptyText: "The server responded successfully, but the feed is empty.",
      freeDelivery: "Free delivery",
      deliveryAvailable: "Delivery available",
      newRating: "New",
      all: "All",
      clear: "Clear",
    },
    search: {
      title: "Search",
      placeholder: "Restaurant, cuisine or dish",
      clear: "Clear",
      failed: "Search did not load",
      restaurants: "Restaurants",
      dishes: "Dishes",
      indexed: "Indexed",
      quick: "Quick search",
      open: "Open",
      emptyTitle: "No results",
      emptyText: "Try a cuisine, restaurant or dish from the live menu.",
    },
    account: {
      title: "Account",
      action: "Settings",
      customer: "Tagam customer",
      subtitle: "Rewards, wallet and saved addresses",
      preferences: "App preferences",
      language: "Language",
      theme: "Theme",
      dark: "Dark",
      light: "Light",
      done: "Done",
      appliesImmediately: "Changes apply instantly across the app.",
      metrics: ["Reward points", "Wallet balance", "Saved places", "Reorder rate"],
      menu: ["Orders", "Payments", "Addresses", "Notifications", "Language & theme"],
    },
    location: {
      title: "Choose address",
      action: "Location",
      guestTitle: "You can create an account later",
      guestText:
        "For now we only need your delivery address. Registration can come later for saved addresses, order history, wallet and payments.",
      login: "Sign in",
      guest: "Continue as guest",
      mapHint: "Choose a point on the map",
      pinTitle: "Drop a pin on the map",
      checking: "Checking address...",
      confirm: "Confirm location",
    },
    restaurant: {
      save: "Save restaurant",
      unavailable: "Restaurant unavailable",
      retry: "Retry",
      newRating: "New",
      distance: "Distance",
      distanceAway: "away",
      deals: "Deals",
      noDeals: "No deals",
      items: "Items",
      menuEmpty: "Menu is empty",
      menuEmptyText: "The restaurant is available, but menu items are not published right now.",
      itemCount: "items",
      sale: "Sale",
      noDescription: "Description coming soon",
      openItem: "Open item details",
      cart: "Cart",
      km: "km",
      from: "from",
      popular: "Popular",
      menu: "Menu",
      deliveryAvailable: "Delivery available",
    },
    tracking: {
      title: "Order tracking",
      action: "Open chat",
      eta: "Arriving in 12 min",
      headline: "Your courier is near Neutrality Avenue.",
      liveRoute: "Live route",
      steps: [
        ["Restaurant accepted", "Kitchen started your order", true],
        ["Courier picked up", "Live route and chat enabled", true],
        ["Almost there", "Prepare for contactless handoff", false],
      ],
    },
  },
};

export const useAppStore = defineStore("app", {
  state: () => ({
    locationLabel: "Ashgabat",
    cartCount: 0,
    language: LocalStorage.getItem(languageKey) || "ru",
    theme: LocalStorage.getItem(themeKey) || "dark",
    currency: LocalStorage.getItem(currencyKey) || "TMT",
    promo: {
      title: "Free delivery tonight",
      subtitle: "Selected restaurants near you",
    },
  }),
  getters: {
    darkMode: (state) => state.theme === "dark",
    copy: (state) => copy[state.language] || copy.ru,
  },
  actions: {
    initPreferences() {
      applyTheme(this.theme);
      document.documentElement.lang = this.language;
    },
    setLanguage(language) {
      this.language = language;
      LocalStorage.set(languageKey, language);
      document.documentElement.lang = language;
    },
    setTheme(theme) {
      this.theme = theme === "light" ? "light" : "dark";
      LocalStorage.set(themeKey, this.theme);
      applyTheme(this.theme);
    },
    setCurrency(currency) {
      if (!currency) return;
      this.currency = currency;
      LocalStorage.set(currencyKey, currency);
    },
    toggleTheme() {
      this.setTheme(this.theme === "dark" ? "light" : "dark");
    },
  },
});
